In [1]:
import numpy as np
import pandas as pd

In [3]:
census = pd.read_csv("census.csv")
census

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
1,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243286,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
2,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
3,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
4,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3138,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3139,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3140,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3141,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [32]:
sm = census.iloc[:,5:7]
sm

       STNAME            CTYNAME
0     Alabama     Autauga County
1     Alabama     Baldwin County
2     Alabama     Barbour County
3     Alabama        Bibb County
4     Alabama      Blount County
...       ...                ...
3137  Wyoming  Sweetwater County
3138  Wyoming       Teton County
3139  Wyoming       Uinta County
3140  Wyoming    Washakie County
3141  Wyoming      Weston County

[3142 rows x 2 columns]

In [35]:
sm2 = sm.groupby("STNAME")
c1 = sm2.count()
c1

                      CTYNAME
STNAME
Alabama                    67
Alaska                     29
Arizona                    15
Arkansas                   75
California                 58
Colorado                   64
Connecticut                 8
Delaware                    3
District of Columbia        1
Florida                    67
Georgia                   159
Hawaii                      5
Idaho                      44
Illinois                  102
Indiana                    92
Iowa                       99
Kansas                    105
Kentucky                  120
Louisiana                  64
Maine                      16
Maryland                   24
Massachusetts              14
Michigan                   83
Minnesota                  87
Mississippi                82
Missouri                  115
Montana                    56
Nebraska                   93
Nevada                     17
New Hampshire              10
New Jersey                 21
New Mexico                 33
New York                   62
North Carolina            100
North Dakota               53
Ohio                       88
Oklahoma                   77
Oregon                     36
Pennsylvania               67
Rhode Island                5
South Carolina             46
South Dakota               66
Tennessee                  95
Texas                     254
Utah                       29
Vermont                    14
Virginia                  133
Washington                 39
West Virginia              55
Wisconsin                  72
Wyoming                    23

In [50]:
max(c1.iloc[:,0])

254

In [54]:
n = len(c1.iloc[:,0])
k=0
for i in range(n):
    k+=1
    if(c1.iloc[i,0]==max(c1.iloc[:,0])):
        break
c1.iloc[k-1]

CTYNAME    254
Name: Texas, dtype: int64

In [62]:
census

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
1,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243286,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
2,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
3,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
4,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3138,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3139,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3140,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3141,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [65]:
sm4 = census.iloc[:,5:8]
sm4

       STNAME            CTYNAME  CENSUS2010POP
0     Alabama     Autauga County          54571
1     Alabama     Baldwin County         182265
2     Alabama     Barbour County          27457
3     Alabama        Bibb County          22915
4     Alabama      Blount County          57322
...       ...                ...            ...
3137  Wyoming  Sweetwater County          43806
3138  Wyoming       Teton County          21294
3139  Wyoming       Uinta County          21118
3140  Wyoming    Washakie County           8533
3141  Wyoming      Weston County           7208

[3142 rows x 3 columns]

In [66]:
sm5 = sm4.groupby("STNAME")
c5 = sm4.sum("CENSUS2010POP")
c5

ValueError: No axis named CENSUS2010POP for object type <class 'pandas.core.frame.DataFrame'>